version: '3'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestjs_tutor
      MYSQL_USER: bank
      MYSQL_PASSWORD: test
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:


networks:
  default:
    driver: bridge
